- name: Playbook to install docker and run wordpress as container
  become: yes
  hosts: towertest2
  tasks:
    - apt: name ={{item}} state=present 
      with_items:
        - python-setuptools
        - python-pip
        - docker
        - docker.io
        - python-dev 
        - build-essential 

    - command: easy_install pip

    - pip : name={{item}}
      with_items:
        - docker-compose
        - docker-py
        - pyyaml

    - docker_service:
        project_src: wordress
        build: yes
        state: present
      register: output
