- name: Playbook to install docker and run wordpress as container
  hosts: towertest2
  tasks:
    - apt: name ={{ item }} state=present update_cache=yes
      with_items:
        - docker
        - docker.io

    - docker_service:
        project_src: wordress
        build: yes
        state: present
      register: output
